name: Feature Request
description: Request a new or improved a feature in SPARTAN UI
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Please search GitHub for a similar [issue](https://github.com/goetzrobin/spartan/issues) or [PR](https://github.com/goetzrobin/spartan/issues)  before submitting a new issue.
  - type: dropdown
    id: type_bug
    attributes:
      label: Which scope/s are relevant/related to the feature request?
      options:
        - accordion
        - alert
        - alert-dialog
        - aspect-ratio
        - avatar
        - badge
        - button
        - calendar
        - card
        - checkbox
        - collapsible
        - combobox
        - command
        - context-menu
        - data-table
        - date-picker
        - dialog
        - dropdown-menu
        - hover-card
        - input
        - label
        - menubar
        - navigation-menu
        - pagination
        - popover
        - progress
        - radio-group
        - scroll-area
        - select
        - separator
        - sheet
        - skeleton
        - slider
        - switch
        - table
        - tabs
        - textarea
        - toast
        - toggle
        - tooltip
        - trpc
        - typography
        - Docs
        - Don't know / other
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: Information
      description: Tell us what you want to be added to SPARTAN UI
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe any alternatives/workarounds you're currently using

  - type: checkboxes
    id: assistance
    attributes:
      label: I would be willing to submit a PR to fix this issue
      description: Assistance is provided if you need help submitting a pull request
      options:
        - label: 'Yes'
        - label: 'No'
